export const portfolioSkills = [
  {
    title: "HighJump AI",
    subtitle: "AI companion for outbound sales",
    image: "./highjump-illustration.png",
    alt: "HighJump AI - AI companion for outbound sales",
    web: [
      "Web Development",
      "ReactJS",
      "NextJS",
      "JavaScript",
      "Chrome Extension",
    ],
    backEnd: ["NodeJS"],
    api: ["API Integration", "OpenAI"],
    skillsDb: ["Prisma", "Vercel"],
  },
  {
    title: "FreshCurrencies",
    subtitle: "FreshBooks Add-on with FreshBooks and Stripe API Integrations",
    image: "./freshcurrencies-portfolio.png",
    alt: "FreshCurrencies - FreshBooks add-on with Stripe API Integration",
    web: ["Web Development", "JavaScript", "CSS"],
    backEnd: ["Python", "postgreSQL"],
    api: ["API Integration", "Django", "Stripe API", "FreshBooks API", "REST"],
    skillsDb: ["Digital Ocean"],
  },
  {
    title: "FreshBooks",
    subtitle: "FreshBooks - Various Front-End and Back-End projects",
    image: "./freshbooks-reports.png",
    alt: "FreshBooks - Accounting Reports",
    web: ["Web Development", "EmberJS", "JavaScript", "CSS"],
    backEnd: ["Python", "mySQL", "PHP"],
    api: ["API Integration", "OCR"],
  },
  {
    title: "Babysitting Whistler",
    subtitle: "Booking Form and API Integration",
    image: "./babysittingwhistler-portfolio.png",
    alt: "Babysitting Whistler - Booking Form and API Integration",
    web: ["Web Development", "ReactJS", "JavaScript", "CSS"],
    backEnd: ["Python", "mySQL"],
    api: ["API Integration", "WhenIWork", "Stripe", "REST"],
    skillsDb: ["Digital Ocean"],
  },
  {
    title: "Caddie",
    subtitle: "Prototype (MVP)",
    image: "./caddie-portfolio.png",
    alt: "Caddie MVP",
    web: ["Web Development", "ReactJS", "JavaScript", "CSS"],
    backEnd: ["Python", "mySQL", "Django REST"],
  },
  {
    title: "Teazit",
    subtitle: "Live-streaming platform for clubs, bars and events",
    image: "./teazit.jpeg",
    alt: "Teazit web app",
    web: ["Web Development", "EmberJS", "Bulma"],
    backEnd: ["Python", "mySQL"],
    api: ["API Integration", "REST", "ZenDesk"],
  },
  {
    title: "FreshBooks Support",
    subtitle: "Custom API implementation with ZenDesk",
    image: "./zendesk-api.png",
    alt: "Custom ZenDesk API",
    backEnd: ["Python", "mySQL"],
    api: ["API Integration", "REST", "ZenDesk"],
  },
];
